// <auto-generated />
namespace SimpleCMS.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_tags_to_Post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tags_to_Post));
        
        string IMigrationMetadata.Id
        {
            get { return "202108160914373_add_tags_to_Post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
